let date = new Date();

document.write(date);
document.write("<br>");
document.write(date.toDateString());
document.write("<br>");
document.write(date.toTimeString());
document.write("<br>");
document.write(date.toTimeString().substring(0, 8));
document.write("<br>");
document.write(date.getTime());
document.write("<br>");
document.write(Date.parse(date));
document.write("<br>");
document.write(date.getFullYear());
document.write("<br>");
document.write(date.getYear());
document.write("<br>");
document.write(date.getDay());
document.write("<br>");
document.write(date.getHours());
document.write("<br>");
document.write(date.getMinutes());
document.write("<br>");
document.write(date.getSeconds());
document.write("<br>");
document.write(date.getMilliseconds());
document.write("<br>");
document.write(setDate(5));
document.write("<br>");
document.write(setYear(2025));
document.write("<br>");
document.write(date);
document.write("<br>");
date = new Date("July 5, 2024 12:58:05");
document.write("<br>");
document.write(date);
date = new Date(1998, 9, 15, 25, 25, 1500);
document.write("<br>");
document.write(date)