#include<stdio.h>
int main()
{
	char strRN[20],strSN[20];
	int t=1;
	printf("Enter the name of the receiver:");
	gets(strRN);
	printf("Enter the name of the sender:");
	gets(strSN);
	printf("Happy");
	sleep(t); 
	printf("\nBirthday");
	sleep(t);
	printf("\n%s",strRN);
	sleep(t);
	printf("\n:)");
	sleep(t);
	printf("\n\nH");
	sleep(t);
	printf("\nA");
	sleep(t);
	printf("\nP");
	sleep(t);
	printf("\nP");
	sleep(t);
	printf("\nY");
	sleep(t);
	printf("\n");
	sleep(t);
	printf("\nB");
	sleep(t);
	printf("\nI");
	sleep(t);
	printf("\nR");
	sleep(t);
	printf("\nT");
	sleep(t);
	printf("\nH");
	sleep(t);
	printf("\nD");
	sleep(t);
	printf("\nA");
	sleep(t);
	printf("\nY");
	sleep(t);
	printf("\n!");
	sleep(t);
	printf("\n");
	sleep(t);
	printf("\nMay");
	sleep(t);
	printf(" you");
	sleep(t);
	printf(" be");
	sleep(t);
	printf(" happy");
	sleep(t);
	printf(",healthy");
	sleep(t);
	printf(",wealthy");
	sleep(t);
	printf(",successful");
	sleep(t);
	printf(",lucky");
	sleep(t);
	printf(",fortunate");
	sleep(t);
	printf(" and");
	sleep(t);
	printf(" blessed");
	sleep(t);
	printf(" by");
	sleep(t);
	printf(" god");
	sleep(t);
	printf(" throughout");
	sleep(t);
	printf(" your");
	sleep(t);
	printf(" life\n");
	sleep(t);
	printf("\nEagerly waiting to wish you on your next birthday too!\n");
	sleep(t);
	printf("From:\nYours truly\n%s",strSN);
	return 0;
}
